### ISSUE TITLE
cb called synchronously in db._close(cb)

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level.js#109]

**Comment by ralphtheninja** [comment]
Side note: Is it possible for the close operation to error? Technically that is, code wise it never errors.

**Comment by vweevers** [comment]
AFAIK only if you create a new transaction while the db is closing (that transaction will error).

**Comment by vweevers** [comment]
Yea, other than that, the spec makes no mention of close errors: https://www.w3.org/TR/IndexedDB-2/#closing-connection.
