### ISSUE TITLE
Tests hang on Firefox 52.8

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level.js#113]
![screenshot from 2018-05-26 22-42-18](https://user-images.githubusercontent.com/308049/40580027-2f42ecde-6136-11e8-933e-63a1ffaeee0d.png)

**Comment by vweevers** [comment]
Can you paste the console output?

**Comment by ralphtheninja** [comment]
![screenshot from 2018-05-27 12-53-13](https://user-images.githubusercontent.com/308049/40585099-f7b65630-61ac-11e8-8a3f-b5ff25a97ad9.png)

**Comment by vweevers** [comment]
Firefox 52 is pretty old though, for an evergreen browser.

**Comment by ralphtheninja** [comment]
Ok. It's what I got on Debian atm. I should update then.
