### ISSUE TITLE
Array Buffers

### ISSUE THREAD

**Issue by calvinmetcalf** [Level/level.js#34]
If I try to put array buffer into a db that has valueEncoding set to 'binary' I get an error about 

```
message: "value cannot be an empty ArrayBuffer"
name: "WriteError"
```

as far as I can tell this is due to it being improperly turned into a Uint8 at some point, I managed to trace it to [here](https://github.com/rvagg/node-levelup/blob/master/lib/util.js#L35) where the array Buffer failed the Buffer.isBuffer test, but then when new Buffer(ArrayBuffer) is called it uses ArrayBuffer.prototype.length instead of ArrayBuffer.prototype.byteLength, so I'll likely have to open an issue there as well

**Comment by feross** [comment]
Btw, my comment was from 2014! I think Node.js is moving towards supporting `Uint8Array` and `ArrayBuffer` in built-in modules like `fs`, etc. Just FYI

**Comment by vweevers** [comment]
Interesting! I guess we might restore ArrayBuffer support at some point, but the Level ecosystem is pretty much Buffer-only so for now we're good.

**Comment by feross** [comment]
Sounds good, consistency is more important!

**Comment by vweevers** [comment]
FTR, we actually *do* support `ArrayBuffer`. I did not intend it but lol it just works 😄.

You can `put` an `ArrayBuffer` and it will come back as a Buffer by default, or an `ArrayBuffer` if you do `get(key, { asBuffer: false })`. When iterating binary keys, they will come back as Buffer by default, or an `ArrayBuffer` if you do `iterator({ keyAsBuffer: false })`.
