### ISSUE TITLE
abstract-leveldown tests aren't all passing anymore

### ISSUE THREAD

**Issue by maxogden** [Level/level.js#40]
right now the tests don't pass in latest chrome. Not sure if it was something in chrome, idb-wrapper, or abstract-leveldown that changed but if someone has some time to dig in and try and make the tests pass it would be much appreciated

**Comment by mcollina** [comment]
I max, I think you bumped abstract-leveldown too far, and the module is now broken. From 0.12 to 2.4 there are plenty of breaking changes: https://github.com/maxogden/level.js/commit/e693249b26c2186e219a2b057648d537cee96d49.

I hope to have a look asap.

**Comment by gritzko** [comment]
0.12 behavior differs from 2.4
For example, it rebels against empty values.
Quite an annoyance.

**Comment by ralphtheninja** [comment]
@maxogden @mcollina I'm actively working on this right now and I'd love to see this repository moved to the `level` org. @juliangruber and @vweevers are also very active.

**Comment by ralphtheninja** [comment]
> 0.12 behavior differs from 2.4
> For example, it rebels against empty values.
> Quite an annoyance.

@gritzko We want to take stuff like that out of `abstract-leveldown` in a new major version. `abstract-leveldown` should basically assume nothing about serialization of different *downs.
