### ISSUE TITLE
snapshots seem not to work

### ISSUE THREAD

**Issue by juliangruber** [Level/level.js#43]
this test (simplified for this issue):

``` js
test('iterator create snapshot correctly', function (t) {
    db.put('foobatch1', 'bar1', function(err){
      t.error(err)
      var iterator = db.iterator()
      db.del('foobatch1', function () {
        iterator.next(function (err, key, value) {
          t.notOk(err, 'no error')
          t.ok(key, 'got a key')
          t.equal(key.toString(), 'foobatch1', 'correct key')
          t.equal(value.toString(), 'bar1', 'correct value')
          iterator.end(t.end.bind(t))
        })
      })
    })
  })
```

is failing:

```
# iterator create snapshot correctly
default_stream.js:27 ok 419 no error
default_stream.js:27 not ok 420 got a key
default_stream.js:27   ---
default_stream.js:27     operator: ok
default_stream.js:27     expected: true
default_stream.js:27     actual:   undefined
default_stream.js:27     at: Test.assert (http://localhost:9966/test.js:12977:17)
default_stream.js:27   ...
iterator-test.js:467 Uncaught TypeError: Cannot read property 'toString' of undefined
```

@maxogden do you know what's going on here?

**Comment by ralphtheninja** [comment]
@juliangruber Just noticed this myself while trying to bring `level.js` up to par on `abstract-levelown`. It seems that it doesn't have support for snapshots and that needs to be implemented.

**Comment by juliangruber** [comment]
Can we implement snapshots after we bring the rest up to par? It seems like this is it's own good chunk of work.

**Comment by vweevers** [comment]
The thing with IndexedDB is that you can't have both snapshots and proper backpressure. Details in the thread starting here: https://github.com/maxogden/level.js/issues/46#issuecomment-183709506

**Comment by vweevers** [comment]
> I checked memdown and it seems it grabs the tree from the db, which I think is why it works well for memdown

Memdown is a different story. It works because it's backed by [functional-red-black-tree](https://github.com/mikolalysenko/functional-red-black-tree) which is a [persistent data structure](https://en.wikipedia.org/wiki/Persistent_data_structure). I.e. iteration happens on an immutable tree, unaffected by simultaneous writes.
