### ISSUE TITLE
level-js@2.2.4 depends on outdated xtend@~2.1.2 (current version is 4.0.1)

### ISSUE THREAD

**Issue by ShadSterling** [Level/level.js#56]
`npm install` gives this warning:
```
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
```

`npm ls object-keys` shows it as an indirect dependency of `level-js`:
```
│     └─┬ level-js@2.2.4
│       └─┬ xtend@2.1.2
│         └── object-keys@0.4.0
```

Reading `npm info` shows that `level-js@2.2.4` is the current version, and depends on an outdated version of `xtend`.

**Comment by ralphtheninja** [comment]
@Polyergic You're right. There are also other dependencies that are heavily outdated, but we have begun working on it :)
