### ISSUE TITLE
Remove non-standard raw option

### ISSUE THREAD

**Issue by vweevers** [Level/level.js#65]
https://github.com/Level/level.js/blob/e819338e87aa305e57ec9c2fe58168ab5dca6da3/index.js#L47-L53

**Comment by vweevers** [comment]
@ralphtheninja the idea of the upgrading label is to remember breaking changes?

**Comment by ralphtheninja** [comment]
@vweevers Exactly!

**Comment by vweevers** [comment]
In `UPGRADING.md` we can mention the `id` encoding, which is the "idiomatic" way to do what `raw` does here.
