### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level.js#69]

**Comment by ralphtheninja** [comment]
@vweevers I've added tags retroactively, in case you wonder why there are a gazillion builds of old versions on travis.

**Comment by vweevers** [comment]
I don't see any builds in Travis but 👍

**Comment by ralphtheninja** [comment]
> I don't see any builds in Travis but +1

Aaah ok. I figured I just give you a heads up since it happened before on other repos.
