### ISSUE TITLE
Fix aborting on end

### ISSUE THREAD

**Issue by vweevers** [Level/level.js#77]
We get random errors (screenshot from Sauce Labs):

![image](https://user-images.githubusercontent.com/3055345/40437934-fc647174-5eb6-11e8-8ad4-d44c3565cb00.png)

**Comment by vweevers** [comment]
There are actually 3 problems:

1. When we call `transaction.abort` in `iterator._end`, we should wait for `transaction.onabort` (which is async) before calling back. Easy fix.
2. When we abort a transaction, but a request within that transaction is pending, the request will emit an error (which IDBWrapper treats as if the transaction errored). Sort of handled already, because in our error handler, we check whether the iterator has `_ended` and if so, we ignore the error. But it's something to keep in mind when we remove IDBWrapper.
3. Occasionally (once every few hundred repeated tests), transactions complete internally before they have emitted `complete`, and cannot be aborted anymore (this is the error shown above). At least in Chrome. And because there is no other way to know that the transaction completed, we must try/catch the `transaction.abort()`.

**Comment by vweevers** [comment]
4. And once every 1000 repeated tests, `transaction.abort()` doesn't throw or lead to an `abort` event, but the transaction does emit `complete` afterwards. Riiight.

**Comment by ralphtheninja** [comment]
Oh gaaawd.

**Comment by vweevers** [comment]
I think I've got a stable solution. Will PR after a good night's sleep. It may not be the cleanest solution, but we can revisit when we remove IDBWrapper. I reckon things like these are easier to tackle if we handle all state changes ourselves.

**Comment by ralphtheninja** [comment]
> Will PR after a good night's sleep.

That's usually a good strategy. Especially when your head is full of stuff.

**Comment by vweevers** [comment]
Ooh it just hit me: we don't have to use `transaction.abort` at all. Instead, simply stop advancing the cursor, and the transaction will complete in the next tick. Yessss
