### ISSUE TITLE
Add more browsers to Sauce Labs

### ISSUE THREAD

**Issue by vweevers** [Level/level.js#89]
Current: Chrome latest and FF latest. Add:

- [x] Edge
- [x] Safari
- [x] IE11
- [ ] ~~More Chrome or FF versions?~~ Nah, they're evergreen.
- [ ] ..?

**Comment by vweevers** [comment]
Depending on which browsers we add, we might be able to remove the shim.

**Comment by vweevers** [comment]
Safari passes tests.

**Comment by vweevers** [comment]
Edge latest (17) fails on array keys.

**Comment by vweevers** [comment]
IE 11 fails on:

- `Number.isNaN`. Can use global `isNaN` instead.
- Use of `Promise` in `levelup`. Should include the same polyfill here.

**Comment by ralphtheninja** [comment]
> Depending on which browsers we add, we might be able to remove the shim.

Which shim?

**Comment by vweevers** [comment]
https://github.com/Level/level.js/blob/b1c01a9a9c144d462c330fd09fd541baff6b5467/test/test.js#L5-L6
