### ISSUE TITLE
Release 3.0.0-rc1

### ISSUE THREAD

**Issue by vweevers** [Level/level.js#90]
@ralphtheninja when the [v3 milestone](https://github.com/Level/level.js/milestone/1) is done, let's do an RC here too?

**Comment by vweevers** [comment]
And we could also do that before tackling the readme, changelog, upgrade guide, etc.

**Comment by ralphtheninja** [comment]
> @ralphtheninja when the v3 milestone is done, let's do an RC here too?

:+1:

**Comment by ralphtheninja** [comment]
> And we could also do that before tackling the readme, changelog, upgrade guide, etc.

Aye. Let's make an `rc1` with just the code and work on the README after that. I think it should have the same layout as `leveldown` but I guess with extra browser specific section(s).

I can still finish off CHANGELOG for the current history (before your changes) so we have a starting point.

**Comment by ralphtheninja** [comment]
@vweevers We should publish rc's of `level-browserify` as well then.

**Comment by vweevers** [comment]
@ralphtheninja Next week I won't be available as much so I wanna do some light work on the readme and then release. Rest of the milestone can wait IMO.

**Comment by vweevers** [comment]
Remember to use the `next` tag when publishing.

**Comment by vweevers** [comment]
> I can still finish off CHANGELOG for the current history

@ralphtheninja do you want to include that or shall I release now?

**Comment by ralphtheninja** [comment]
> @ralphtheninja do you want to include that or shall I release now?

You can release now. I've barely started on it.

**Comment by vweevers** [comment]
[![npm next](https://img.shields.io/npm/v/level-js/next.svg)](https://www.npmjs.com/package/level-js)
